### ISSUE TITLE
Support for reading pdb.gz file

### ISSUE THREAD

**Issue by Rohit-Satyam** [johnnytam100/AlphaCutter#4]
Hi @johnnytam100 

Is it possible to have functionality where we don't have to decompress the PDB files and run AlphaCutter on them? When working with more than 5K of proteins sometimes decompressing would take a lot of storage.

**Comment by johnnytam100** [comment]
Hi @Rohit-Satyam , thanks for contacting.
Seems pcmap that I used to calculate contact map does not support direct reading from .pdb.gz so currently it's hard to implement but will be my TODO list.
